# Generated by Django 5.1.7 on 2025-03-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseSim', '0002_profile_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(default='foo', max_length=255, null=True),
        ),
    ]
