# Generated by Django 5.1.7 on 2025-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseSim', '0005_case_skin_userinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='skin_src',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
